name: Offline installation test
on:
  push:
  pull_request:
    paths:
      - 'unattended_installer/passwords_tool/**'

jobs:
  Build-wazuh-install-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build wazuh-install script and use pre-release packages
        working-directory: ./unattended_installer
        run: |
          bash builder.sh -i -d
          sed -i 's|wazuh_major="4\.5"|wazuh_major="4\.4"|g' wazuh-install.sh
          sed -i 's|wazuh_version="4\.5\(.*\)"|wazuh_version="4\.4\1"|g' wazuh-install.sh
        shell: bash
      - uses: actions/upload-artifact@v3
        with:
          name: script
          path: |
            unattended_installer/wazuh-install.sh
          if-no-files-found: error
          
  Test-offline-installation-debian:
    runs-on: ubuntu-latest
    needs: Build-wazuh-install-script
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
        with:
          name: script
      - name: Move unattended script
        run: cp $GITHUB_WORKSPACE/wazuh-install.sh $GITHUB_WORKSPACE/.github/actions/offline-installation/wazuh-install.sh
      - name: List files
        run: ls -l $GITHUB_WORKSPACE/.github/actions/offline-installation/
      - name: Run script
        run: sudo bash $GITHUB_WORKSPACE/.github/actions/offline-installation/offline-installation.sh

  Test-offline-installation-rpm:
    runs-on: ubuntu-latest
    needs: Build-wazuh-install-script
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
        with:
          name: script
      - name: Move unattended script
        run: cp $GITHUB_WORKSPACE/wazuh-install.sh $GITHUB_WORKSPACE/.github/actions/offline-installation/wazuh-install.sh
      - name: List files
        run: ls -l $GITHUB_WORKSPACE/.github/actions/offline-installation/
      - name: Launch docker and run script
        run: sudo docker run --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:rw --cgroups -v $GITHUB_WORKSPACE/.github/actions/offline-installation/:/tests centos:centos7 bash /tests/offline-installation.sh
