name: Test Wazuh indexer on upgrade - Debian
on:
  pull_request:
    paths:
      - 'stack/indexer/deb/debian/postrm'
      - 'stack/indexer/deb/debian/postinst'
      - 'stack/indexer/deb/debian/preinst'

jobs:
  Test-debian-indexer-upgrade:
    runs-on: ubuntu-latest
    steps:
      - name: Build wazuh-indexer 4.3 package
        uses: actions/checkout@v3
        with:
          ref: 4.3
        working-directory: ./stack/indexer/deb
        run: |
          ./build_package.sh
          mv ./output/wazuh-indexer_4.3.10-1_amd64.deb ~/wazuh-indexer_4.3.10-1_amd64.deb
      - name: Build wazuh-indexer issue-branch package
        uses: actions/checkout@v3
        with:
          ref: 1850-wazuh-indexer-preserve-config-files-upon-upgrade-master
        working-directory: ./stack/indexer/deb
        run: |
          ./build_package.sh
          mv ./output/wazuh-indexer_4.5.0-1_amd64.deb ~/wazuh-indexer_4.5.0-1_amd64.deb
      - name: Run script
        run: sudo bash .github/actions/upgrade-indexer/upgrade-indexer-debian.sh